export const errorMessages = {
  required: (field: string) => `${field} không được để trống.`,
  minLength: (field: string, minLength: number) =>
    `${field} phải có ít nhất ${minLength} ký tự.`,
  maxLength: (field: string, maxLength: number) =>
    `${field} không được vượt quá ${maxLength} ký tự.`,
  invalidNumber: 'Giá trị phải là số.',
  invalidUUID: 'ID không hợp lệ.',
  invalidSortDir: 'Hướng sắp xếp không hợp lệ (asc hoặc desc).',
  invalidOrderBy: 'Trường sắp xếp không hợp lệ.',
  invalidStatus: 'Trạng thái không hợp lệ.',
  invalidDate: 'Định dạng ngày không hợp lệ.',
  invalidUrl: 'URL không hợp lệ.',
  invalidBoolean: 'Giá trị phải là true hoặc false.',
  invalidEmail: 'Email không hợp lệ.',
  invalidPhone: 'Số điện thoại không hợp lệ.',
  invalidPassword: 'Mật khẩu không hợp lệ.',
  invalidConfirmPassword: 'Mật khẩu xác nhận không khớp.',
  invalidName: 'Tên không hợp lệ.',
  invalidAddress: 'Địa chỉ không hợp lệ.',
  invalidGender: 'Giới tính không hợp lệ.',
  invalidDateOfBirth: 'Ngày sinh không hợp lệ.',
  invalidRole: 'Vai trò không hợp lệ.',
  invalidDepartment: 'Phòng ban không hợp lệ.',
  invalidPosition: 'Vị trí không hợp lệ.',
  invalidStartDate: 'Ngày bắt đầu không hợp lệ.',
  invalidEndDate: 'Ngày kết thúc không hợp lệ.',
  invalidUserType: 'Loại người dùng không hợp lệ.',
  invalidObject: 'Đối tượng không hợp lệ.',
};
